only:let's try to get console .exe-file name before we rewrite autoupdate .jar file to avoid `java.lang.NoClassDefFoundError: com/rusefi/autoupdate/ConsoleExeFileLocator`
(cherry picked from commit 4e2084c0ee25cb20de06c98d0379f497cb412de1)